"""Inital Migration

Revision ID: c74e5fbd7389
Revises: 
Create Date: 2022-03-03 21:46:11.523080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c74e5fbd7389'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Adresse',
    sa.Column('idAdresse', sa.Integer(), nullable=False),
    sa.Column('straße', sa.String(length=45), nullable=False),
    sa.Column('hausnummer', sa.String(length=45), nullable=True),
    sa.Column('postleitzahl', sa.String(length=45), nullable=True),
    sa.Column('ort', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idAdresse')
    )
    op.create_table('Kategorie',
    sa.Column('idKategorie', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('istZaehlbar', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idKategorie')
    )
    op.create_table('Rolle',
    sa.Column('idRolle', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('schreibenKalender', sa.Boolean(), nullable=True),
    sa.Column('lesenKalender', sa.Boolean(), nullable=True),
    sa.Column('schreibenBenutzer', sa.Boolean(), nullable=True),
    sa.Column('lesenBenutzer', sa.Boolean(), nullable=True),
    sa.Column('schreibenMaterial', sa.Boolean(), nullable=True),
    sa.Column('lesenMaterial', sa.Boolean(), nullable=True),
    sa.Column('schreibenEinstellungen', sa.Boolean(), nullable=True),
    sa.Column('lesenEinstellungen', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('idRolle'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Benutzer',
    sa.Column('benutzername', sa.String(length=45), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('emailAdresse', sa.String(length=45), nullable=False),
    sa.Column('passwort', sa.String(length=45), nullable=False),
    sa.Column('adresseRef', sa.Integer(), nullable=False),
    sa.Column('RolleRef', sa.Integer(), nullable=False),
    sa.Column('eingeloggt', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['RolleRef'], ['Rolle.idRolle'], ),
    sa.ForeignKeyConstraint(['adresseRef'], ['Adresse.idAdresse'], ),
    sa.PrimaryKeyConstraint('benutzername'),
    sa.UniqueConstraint('emailAdresse')
    )
    op.create_index(op.f('ix_Benutzer_RolleRef'), 'Benutzer', ['RolleRef'], unique=False)
    op.create_index(op.f('ix_Benutzer_adresseRef'), 'Benutzer', ['adresseRef'], unique=False)
    op.create_table('Material',
    sa.Column('idMaterial', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('Eigenschaften', sa.Text(), nullable=True),
    sa.Column('Kategorie_idKategorie', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Kategorie_idKategorie'], ['Kategorie.idKategorie'], ),
    sa.PrimaryKeyConstraint('idMaterial')
    )
    op.create_index(op.f('ix_Material_Kategorie_idKategorie'), 'Material', ['Kategorie_idKategorie'], unique=False)
    op.create_table('Aktivitaet',
    sa.Column('idAktivitaet', sa.Integer(), nullable=False),
    sa.Column('MaterialId', sa.Integer(), nullable=False),
    sa.Column('ausgecheckt', sa.DateTime(), nullable=False),
    sa.Column('eingecheckt', sa.DateTime(), nullable=True),
    sa.Column('menge', sa.Integer(), nullable=False),
    sa.Column('ersteller_benutzername', sa.String(length=45), nullable=False),
    sa.Column('bemerkung', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['MaterialId'], ['Material.idMaterial'], ),
    sa.ForeignKeyConstraint(['ersteller_benutzername'], ['Benutzer.benutzername'], ),
    sa.PrimaryKeyConstraint('idAktivitaet')
    )
    op.create_table('Ausleihe',
    sa.Column('idAusleihe', sa.Integer(), nullable=False),
    sa.Column('Benutzer_benutzername', sa.String(length=45), nullable=False),
    sa.Column('empfaenger', sa.String(length=45), nullable=True),
    sa.Column('ts_erstellt', sa.DateTime(), nullable=False),
    sa.Column('ts_von', sa.Date(), nullable=False),
    sa.Column('ts_bis', sa.Date(), nullable=False),
    sa.Column('beschreibung', sa.String(), nullable=True),
    sa.Column('materialien', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['Benutzer_benutzername'], ['Benutzer.benutzername'], ),
    sa.PrimaryKeyConstraint('idAusleihe')
    )
    op.create_index(op.f('ix_Ausleihe_Benutzer_benutzername'), 'Ausleihe', ['Benutzer_benutzername'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Ausleihe_Benutzer_benutzername'), table_name='Ausleihe')
    op.drop_table('Ausleihe')
    op.drop_table('Aktivitaet')
    op.drop_index(op.f('ix_Material_Kategorie_idKategorie'), table_name='Material')
    op.drop_table('Material')
    op.drop_index(op.f('ix_Benutzer_adresseRef'), table_name='Benutzer')
    op.drop_index(op.f('ix_Benutzer_RolleRef'), table_name='Benutzer')
    op.drop_table('Benutzer')
    op.drop_table('Rolle')
    op.drop_table('Kategorie')
    op.drop_table('Adresse')
    # ### end Alembic commands ###
