"""Test migration

Revision ID: de08052b9eb2
Revises: c74e5fbd7389
Create Date: 2022-03-05 19:50:18.739733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de08052b9eb2'
down_revision = 'c74e5fbd7389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('idTest', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('idTest')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###
