"""Add anzeigeName for AuslagenKategorie

Revision ID: 25402355d8fd
Revises: e3268463fd63
Create Date: 2023-03-29 19:32:12.726845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25402355d8fd'
down_revision = 'e3268463fd63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AuslagenKategorie', sa.Column('anzeigeName', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AuslagenKategorie', 'anzeigeName')
    # ### end Alembic commands ###
