"""Initial revision

Revision ID: 26a50766a9eb
Revises: 
Create Date: 2023-02-10 21:08:20.533477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26a50766a9eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Adresse',
    sa.Column('idAdresse', sa.Integer(), nullable=False),
    sa.Column('straße', sa.String(length=45), nullable=False),
    sa.Column('hausnummer', sa.String(length=45), nullable=True),
    sa.Column('postleitzahl', sa.String(length=45), nullable=True),
    sa.Column('ort', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idAdresse')
    )
    op.create_table('Kategorie',
    sa.Column('idKategorie', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('istZaehlbar', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idKategorie')
    )
    op.create_table('Label',
    sa.Column('idLabel', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('datentyp', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idLabel')
    )
    op.create_table('Rolle',
    sa.Column('idRolle', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('schreibenKalender', sa.Boolean(), nullable=True),
    sa.Column('lesenKalender', sa.Boolean(), nullable=True),
    sa.Column('schreibenBenutzer', sa.Boolean(), nullable=True),
    sa.Column('lesenBenutzer', sa.Boolean(), nullable=True),
    sa.Column('schreibenMaterial', sa.Boolean(), nullable=True),
    sa.Column('lesenMaterial', sa.Boolean(), nullable=True),
    sa.Column('schreibenEinstellungen', sa.Boolean(), nullable=True),
    sa.Column('lesenEinstellungen', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('idRolle'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Benutzer',
    sa.Column('benutzername', sa.String(length=45), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('emailAdresse', sa.String(length=45), nullable=False),
    sa.Column('passwort', sa.String(length=45), nullable=False),
    sa.Column('adresseRef', sa.Integer(), nullable=False),
    sa.Column('RolleRef', sa.Integer(), nullable=False),
    sa.Column('eingeloggt', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['RolleRef'], ['Rolle.idRolle'], ),
    sa.ForeignKeyConstraint(['adresseRef'], ['Adresse.idAdresse'], ),
    sa.PrimaryKeyConstraint('benutzername'),
    sa.UniqueConstraint('emailAdresse')
    )
    op.create_index(op.f('ix_Benutzer_RolleRef'), 'Benutzer', ['RolleRef'], unique=False)
    op.create_index(op.f('ix_Benutzer_adresseRef'), 'Benutzer', ['adresseRef'], unique=False)
    op.create_table('Material',
    sa.Column('idMaterial', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('Eigenschaften', sa.JSON(), nullable=True),
    sa.Column('Kategorie_idKategorie', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Kategorie_idKategorie'], ['Kategorie.idKategorie'], ),
    sa.PrimaryKeyConstraint('idMaterial')
    )
    op.create_index(op.f('ix_Material_Kategorie_idKategorie'), 'Material', ['Kategorie_idKategorie'], unique=False)
    op.create_table('Standarteigenschaft',
    sa.Column('Kategorie_idKategorie', sa.Integer(), nullable=False),
    sa.Column('Label_idLabel', sa.Integer(), nullable=False),
    sa.Column('wertInt', sa.String(length=45), nullable=True),
    sa.Column('wertString', sa.String(length=45), nullable=True),
    sa.Column('wertBool', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['Kategorie_idKategorie'], ['Kategorie.idKategorie'], ),
    sa.ForeignKeyConstraint(['Label_idLabel'], ['Label.idLabel'], ),
    sa.PrimaryKeyConstraint('Kategorie_idKategorie', 'Label_idLabel')
    )
    op.create_index(op.f('ix_Standarteigenschaft_Kategorie_idKategorie'), 'Standarteigenschaft', ['Kategorie_idKategorie'], unique=False)
    op.create_index(op.f('ix_Standarteigenschaft_Label_idLabel'), 'Standarteigenschaft', ['Label_idLabel'], unique=False)
    op.create_table('Aktion',
    sa.Column('idAktion', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('beginn', mysql.DATETIME(fsp=4), nullable=False),
    sa.Column('ende', mysql.DATETIME(fsp=4), nullable=False),
    sa.Column('ansprechpartnerRef', sa.String(length=45), nullable=False),
    sa.Column('Adresse_idAdresse', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Adresse_idAdresse'], ['Adresse.idAdresse'], ),
    sa.ForeignKeyConstraint(['ansprechpartnerRef'], ['Benutzer.benutzername'], ),
    sa.PrimaryKeyConstraint('idAktion')
    )
    op.create_index(op.f('ix_Aktion_Adresse_idAdresse'), 'Aktion', ['Adresse_idAdresse'], unique=False)
    op.create_index(op.f('ix_Aktion_ansprechpartnerRef'), 'Aktion', ['ansprechpartnerRef'], unique=False)
    op.create_table('Aktivitaet',
    sa.Column('idAktivitaet', sa.Integer(), nullable=False),
    sa.Column('MaterialId', sa.Integer(), nullable=False),
    sa.Column('ausgecheckt', sa.DateTime(), nullable=False),
    sa.Column('eingecheckt', sa.DateTime(), nullable=True),
    sa.Column('menge', sa.Integer(), nullable=False),
    sa.Column('ersteller_benutzername', sa.String(length=45), nullable=False),
    sa.Column('bemerkung', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['MaterialId'], ['Material.idMaterial'], ),
    sa.ForeignKeyConstraint(['ersteller_benutzername'], ['Benutzer.benutzername'], ),
    sa.PrimaryKeyConstraint('idAktivitaet')
    )
    op.create_table('Ausleihe',
    sa.Column('idAusleihe', sa.Integer(), nullable=False),
    sa.Column('Benutzer_benutzername', sa.String(length=45), nullable=False),
    sa.Column('empfaenger', sa.String(length=45), nullable=True),
    sa.Column('ts_erstellt', sa.DateTime(), nullable=False),
    sa.Column('ts_von', sa.Date(), nullable=False),
    sa.Column('ts_bis', sa.Date(), nullable=False),
    sa.Column('beschreibung', sa.String(), nullable=True),
    sa.Column('materialien', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['Benutzer_benutzername'], ['Benutzer.benutzername'], ),
    sa.PrimaryKeyConstraint('idAusleihe')
    )
    op.create_index(op.f('ix_Ausleihe_Benutzer_benutzername'), 'Ausleihe', ['Benutzer_benutzername'], unique=False)
    op.create_table('Eigenschaft',
    sa.Column('Material_idMaterial', sa.Integer(), nullable=False),
    sa.Column('Label_idLabel', sa.Integer(), nullable=False),
    sa.Column('wertInt', sa.String(length=45), nullable=True),
    sa.Column('wertString', sa.String(length=45), nullable=True),
    sa.Column('wertBool', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['Label_idLabel'], ['Label.idLabel'], ),
    sa.ForeignKeyConstraint(['Material_idMaterial'], ['Material.idMaterial'], ),
    sa.PrimaryKeyConstraint('Material_idMaterial', 'Label_idLabel')
    )
    op.create_index(op.f('ix_Eigenschaft_Label_idLabel'), 'Eigenschaft', ['Label_idLabel'], unique=False)
    op.create_index(op.f('ix_Eigenschaft_Material_idMaterial'), 'Eigenschaft', ['Material_idMaterial'], unique=False)
    op.create_table('Lager',
    sa.Column('idLager', sa.Integer(), nullable=False),
    sa.Column('adresseRef', sa.Integer(), nullable=False),
    sa.Column('ansprechpartnerRef', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['adresseRef'], ['Adresse.idAdresse'], ),
    sa.ForeignKeyConstraint(['ansprechpartnerRef'], ['Benutzer.benutzername'], ),
    sa.PrimaryKeyConstraint('idLager')
    )
    op.create_index(op.f('ix_Lager_adresseRef'), 'Lager', ['adresseRef'], unique=False)
    op.create_index(op.f('ix_Lager_ansprechpartnerRef'), 'Lager', ['ansprechpartnerRef'], unique=False)
    op.create_table('img',
    sa.Column('img_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Material_idMaterial', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('mimetype', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['Material_idMaterial'], ['Material.idMaterial'], ),
    sa.PrimaryKeyConstraint('img_id')
    )
    op.create_index(op.f('ix_img_Material_idMaterial'), 'img', ['Material_idMaterial'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_img_Material_idMaterial'), table_name='img')
    op.drop_table('img')
    op.drop_index(op.f('ix_Lager_ansprechpartnerRef'), table_name='Lager')
    op.drop_index(op.f('ix_Lager_adresseRef'), table_name='Lager')
    op.drop_table('Lager')
    op.drop_index(op.f('ix_Eigenschaft_Material_idMaterial'), table_name='Eigenschaft')
    op.drop_index(op.f('ix_Eigenschaft_Label_idLabel'), table_name='Eigenschaft')
    op.drop_table('Eigenschaft')
    op.drop_index(op.f('ix_Ausleihe_Benutzer_benutzername'), table_name='Ausleihe')
    op.drop_table('Ausleihe')
    op.drop_table('Aktivitaet')
    op.drop_index(op.f('ix_Aktion_ansprechpartnerRef'), table_name='Aktion')
    op.drop_index(op.f('ix_Aktion_Adresse_idAdresse'), table_name='Aktion')
    op.drop_table('Aktion')
    op.drop_index(op.f('ix_Standarteigenschaft_Label_idLabel'), table_name='Standarteigenschaft')
    op.drop_index(op.f('ix_Standarteigenschaft_Kategorie_idKategorie'), table_name='Standarteigenschaft')
    op.drop_table('Standarteigenschaft')
    op.drop_index(op.f('ix_Material_Kategorie_idKategorie'), table_name='Material')
    op.drop_table('Material')
    op.drop_index(op.f('ix_Benutzer_adresseRef'), table_name='Benutzer')
    op.drop_index(op.f('ix_Benutzer_RolleRef'), table_name='Benutzer')
    op.drop_table('Benutzer')
    op.drop_table('Rolle')
    op.drop_table('Label')
    op.drop_table('Kategorie')
    op.drop_table('Adresse')
    # ### end Alembic commands ###
