"""Add Auslagen

Revision ID: e3268463fd63
Revises: 26a50766a9eb
Create Date: 2023-03-27 22:10:58.465532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3268463fd63'
down_revision = '26a50766a9eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AuslagenKategorie',
    sa.Column('idAuslKateg', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idAuslKateg'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Auslage',
    sa.Column('idAuslage', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(length=45), nullable=False),
    sa.Column('betrag', sa.Float(), nullable=False),
    sa.Column('iban', sa.String(length=22), nullable=False),
    sa.Column('bic', sa.String(length=11), nullable=False),
    sa.Column('kontoinhaber', sa.String(length=45), nullable=False),
    sa.Column('grund', sa.String(), nullable=False),
    sa.Column('eingereicht_zeit', sa.DateTime(), nullable=False),
    sa.Column('freigabe_zeit', sa.DateTime(), nullable=True),
    sa.Column('Ersteller_benutzername', sa.String(length=45), nullable=False),
    sa.Column('Freigabe_benutzername', sa.String(length=45), nullable=True),
    sa.Column('erledigt_zeit', sa.DateTime(), nullable=True),
    sa.Column('Erledigt_benutzername', sa.String(length=45), nullable=True),
    sa.Column('AuslagenKategorie_idAuslKateg', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['AuslagenKategorie_idAuslKateg'], ['AuslagenKategorie.idAuslKateg'], ),
    sa.ForeignKeyConstraint(['Ersteller_benutzername'], ['Benutzer.benutzername'], ),
    sa.ForeignKeyConstraint(['Freigabe_benutzername'], ['Benutzer.benutzername'], ),
    sa.ForeignKeyConstraint(['Erledigt_benutzername'], ['Benutzer.benutzername'], ),
    sa.PrimaryKeyConstraint('idAuslage')
    )
    op.create_table('AuslagenBild',
    sa.Column('img_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Auslage_id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('mimetype', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['Auslage_id'], ['Auslage.idAuslage'], ),
    sa.PrimaryKeyConstraint('img_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AuslagenBild')
    op.drop_table('Auslage')
    op.drop_table('AuslagenKategorie')
    # ### end Alembic commands ###
