"""Add IBAN to Benutzer

Revision ID: eaf143f73877
Revises: 31a8c2714505
Create Date: 2023-04-09 14:29:55.615269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaf143f73877'
down_revision = '31a8c2714505'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Benutzer', sa.Column('iban', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Benutzer', 'iban')
    # ### end Alembic commands ###
